# Armar todo y correr
# docker-compose -f ./gateway/docker-compose.yml up --build -d

services:
  gateway:
    image: ms-gateway-svc:latest
    container_name: gateway-svc
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_EUREKA_DEFAULT_ZONE: http://eureka-svc:8761/eureka/
    ports:
      - "3080:8080"
    networks:
      - backend-net

networks:
  backend-net:
    external: true
