# Armar todo y correr
# docker-compose -f ./prometheus/docker-compose.yml up --build -d

services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --log.level=debug
    networks:
      - backend-net
      - prometheus-net


  # Credenciales:
  #   user: admin
  #   pass: admin
  grafana:
    image: 'grafana/grafana:latest'
    ports:
      - 6591:3000
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources      
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
      - prometheus
    networks:
      - backend-net
      - prometheus-net

networks:
  backend-net:
    external: true
  prometheus-net:
    driver: bridge

volumes:
  prometheus-data: