# Armar todo y correr
# docker-compose -f ./prometheus/docker-compose.yml up --build -d

services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --log.level=debug
    networks:
      - backend-net

networks:
  backend-net:
    external: true

volumes:
  prometheus-data: