{
 "title": "TP dan",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "CRUD requests /api/productos",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{uri=\"/api/productos\"}) + sum(http_server_requests_seconds_count{uri=\"/api/productos/{id}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CRUD requests /api/clientes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{uri=\"/api/clientes\"}) + sum(http_server_requests_seconds_count{uri=\"/api/clientes/{id}\"}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CRUD requests /api/pedidos",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{uri=\"/api/pedidos\"}) + sum(http_server_requests_seconds_count{uri=\"/api/pedidos/{id}\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}