# Crear red
# docker network create backend-net

# Armar todo y correr
# docker-compose -f ./ms-docker/docker-compose-rabbit.yml up -d 

version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend-net

networks:
  backend-net:
    external: true
