# Armar todo y correr
# docker-compose -f ./graylog/docker-compose.yml up --build -d

# Ejemplos de configuración:
# https://github.com/Graylog2/docker-compose/blob/main/cluster/docker-compose.yml
# https://go2docs.graylog.org/current/downloading_and_installing_graylog/docker_installation.htm

services:
  mongo:
    image: mongo #mongo:6.0.14
    restart: always
    #ports:
    #  - 27017:27017
    volumes:
      - mongo-data:/data/db
    #environment:
      #MONGO_INITDB_ROOT_USERNAME: graylog-dan-user
      #MONGO_INITDB_ROOT_PASSWORD: graylog-dan-pass
      #MONGO_INITDB_DATABASE: graylog-dan
    networks:
      - graylog-net

  #elasticsearch:
  #  image: elasticsearch:8.14.3
  opensearch:
    image: opensearchproject/opensearch
    restart: always
    volumes:
      - opensearch-data:/data/db
    #ports:
    #  - 9200:9200
    environment:
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: Opensearch-dan-2024-pass
      # Necesarios para solucionar varios errores
      discovery.type: single-node
      plugins.security.ssl.http.enabled: false
      plugins.security.disabled: true
    networks:
      - graylog-net


  # Acceder: http://localhost:9000
  # User: admin
  # Pass: graylog-dan-super-secret
  svc:
    image: graylog/graylog:6.0.4
    volumes:
      - graylog-data:/data
    ports:
      - "9000:9000"        # Interfaz web y REST API
      - "1514:1514"        # Syslog TCP
      - "1514:1514/udp"    # Syslog UDP
      - "12201:12201"      # GELF TCP
      - "12201:12201/udp"  # GELF UDP
    environment:
      GRAYLOG_PASSWORD_SECRET: graylog-dan-super-secret
      # https://tools.keycdn.com/sha256-online-generator
      GRAYLOG_ROOT_PASSWORD_SHA2: db58d428f9a0dae0a30231931ea85ee900ab6cf05bc1113cb41772ad3abe8d98
      GRAYLOG_MONGODB_URI: mongodb://mongo:27017/graylog   #mongodb://graylog-dan-user:graylog-dan-pass@mongo:27017/graylog-dan?authSource=admin
      GRAYLOG_ELASTICSEARCH_HOSTS: http://opensearch:9200
      GRAYLOG_HTTP_EXTERNAL_URI: http://localhost:9000/
    depends_on:
      - mongo
      - opensearch
    networks:
      - graylog-net
      - backend-net

networks:
  backend-net:
    external: true
  graylog-net:
    driver: bridge

volumes:
  mongo-data:
  opensearch-data:
  graylog-data:

