# Crear red
# docker network create backend-net

# Armar todo y correr
# docker-compose -f ./ms-clientes/docker-compose.yml up --build -d

# Troubleshooting
# Comandos: docker image prune -a / docker builder prune -a (limpiar cache imagenes), docker network prune (limpiar redes viejas)
# Asegurarse que Dockerfile y docker-compose tengan "LF" (line feed, linux) y no "CR LF" (carriage return line feed, windows)
# Asegurarse que la arquitectura de la imagen soporte la misma que la de la compu: amd64 -> x86/64, arm64
# No olvidarse de ejecutar Docker desktop

version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: danrootpassword
      MYSQL_DATABASE: dandb
      MYSQL_USER: danuser
      MYSQL_PASSWORD: danpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - clientes-net

  # Acceder desde el navegador: http://localhost:8086/
  phpmyadmin-dan:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: mysql-db
      PMA_USER: danuser
      PMA_PASSWORD: danpassword
    ports:
      - "8086:80"
    depends_on:
      - mysql
    networks:
      - clientes-net

  ms-clientes-svc:
    image: ms-clientes-svc:latest
    container_name: ms-clientes-svc
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/dandb
      SPRING_DATASOURCE_USERNAME: danuser
      SPRING_DATASOURCE_PASSWORD: danpassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      DEFAULT-MAXIMO-DESCUBIERTO: 100000.0
      SPRING_EUREKA_DEFAULT_ZONE: http://ms-eureka-svc:8761/eureka/
      SPRING_INSTANCIA: ms-clientes-svc
      GRAYLOG_HOST: graylog-svc
      GRAYLOG_PORT: 12201
    ports:
      - "6080:8080"
    depends_on:
      - mysql
    networks:
      - clientes-net
      - backend-net
#
networks:
  backend-net:
    external: true
  clientes-net:
    driver: bridge

volumes:
  mysql-data:

